# Change these first
owner: dwarvesf # Your GitHub username
repo: upptime # Your GitHub repository name
user-agent: lmquang
runner: self-hosted
# Add your sites here
sites:
  - name: Fortress API
    url: https://api.fortress.d.foundation/healthz
  - name: MCP DB
    url: https://mcp-db.mcp.d.foundation/healthz
assignees: # Users to assign downtime issues (optional)
  - lmquang
status-website:
  publish: true
  apiBaseUrl: https://proxy.status.d.foundation
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.d.foundation
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  favicon: https://git.d.foundation/uploads/-/system/appearance/favicon/1/LogoD_1024.png
  logoUrl: https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/32c5b772aec460924dbe0d60ce73f1c6.png
  name: Dwarves Foundation Status
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is status page which uses **real-time** data from [Dwarves Foundation](https://dwarves.foundation) services
  # navbar:
  #   - title: Status
  #     href: /
  #   - title: GitHub
  #     href: https://github.com/$OWNER/$REPO
i18n:
  footer: Powered by [Upptime](https://upptime.js.org)
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration