# Change these first
owner: dwarvesf # Your GitHub username
repo: upptime # Your GitHub repository name
user-agent: lmquang
runner: self-hosted
# Add your sites here
sites:
  - name: Fortress API
    url: $FORTRESS_API_URL
  - name: IR API
    url: $IR_API_URL
  - name: ICY swap API
    url: $ICY_API_URL
  - name: Brainery API
    url: $BRAINERY_API_URL
  - name: CGit
    url: $CGIT_URL
    headers:
      - "Authorization: Basic $CGIT_BASIC_AUTH"
  - name: Deepwiki
    url: $DEEPWIKI_URL
  - name: Vault
    url: $VAULT_URL
assignees: # Users to assign downtime issues (optional)
  - lmquang
status-website:
  publish: true
  # apiBaseUrl: https://proxy-api.status.d.foundation
  # userContentBaseUrl: https://proxy-raw.status.d.foundation
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.d.foundation
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  favicon: https://i.ibb.co/fzbXFZr1/svgviewer-png-output.png
  logoUrl: https://i.ibb.co/fzbXFZr1/svgviewer-png-output.png
  name: Dwarves Foundation Status
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is status page which uses **real-time** data from [Dwarves Foundation](https://d.foundation) services
  # navbar:
  #   - title: Status
  #     href: /
  #   - title: GitHub
  #     href: https://github.com/$OWNER/$REPO
i18n:
  footer: Powered by [Upptime](https://upptime.js.org)
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration