apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: upptime-runnerdeploy
  namespace: actions-runner-system-0
spec:
  replicas: 1
  template:
    spec:
      repository: dwarvesf/upptime